name: Build & Release

on:
  push:
    branches: [ master ]

jobs:
  setup:
    name: Setup
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}
  
  release:
    name: Release
    needs: setup
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: Install global Esbuild and Vite commands
        run: npm install --global esbuild vite

      - name: Build App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat scripts/args.esbuild.app-builder | xargs esbuild && node build/app-builder.js
  
