name: CI

on:
  push:
    - tags: 'v*'
    - branches: gh-actions

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-node-

      - name: install
        run: npm install

      - name: cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

  unit-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: test
        run: npm run vtu
  
  build-app:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: build
        run: npm run dist
  
