name: CI

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-node-${{ hashFiles('**/package-lock.json') }}

      - name: install
        run: npm install

      - name: cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

  unit-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: copy env file
        uses: canastro/copy-file-action@master
        with:
          source: "configs/.env-cmdrc.json"
          target: ".env-cmdrc.json"

      - name: test
        run: npm run vtu
  
  build-app:
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Setup Node.js env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: Add global esbuild command
        run: npm install --global esbuild
  
      - name: Build script
        run: esbuild --platform=node --bundle --external:vite --external:esbuild --external:electron-builder scripts/app-builder.ts --outfile=build/app-builder.js

      - name: Build app
        env:
          BUILD_ENV: 'gh-action'
        run: |
          esbuild --platform=node --bundle --minify --external:electron --external:path --external:fs main/main.ts main/preload.ts --outdir=build
          node build/app-builder.js
  
