name: Test

on:
  - push
  - pull_request

jobs:
  setup:
    name: Setup 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

  unit-testing:
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    needs: setup
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}
    
      - name: Install global Esbuild and Vite commands
        run: npm install --global esbuild vite

      - name: Copy env file
        run: cp configs/.env-cmdrc.json .env-cmdrc.json

      - name: Test Vue components
        if: ${{ matrix.os === 'ubuntu-latest' }}
        run: npm run vtu
      
      - name: Test Vue components
        if: ${{ matrix.os === 'macos-latest' }}
        run: cat scripts/args.esbuild.dev-runner | xargs esbuild && env-cmd -e dev,vtu node build/dev-runner.js
  
