name: Test

on:
  pull_request:
    branches:
      - master
      - releases/**
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/**
    paths-ignore:
      - '**.md'

jobs:
  setup:
    name: Unit Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore NPM cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
      - name: Install dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm install --global esbuild vite env-cmd
      - name: Restore workspace
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-cache-${{ github.sha }}
      - name: Copy env file
        run: cp configs/.env-cmdrc.json .env-cmdrc.json
      - name: Test Vue components
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: npm run vtu
      - name: Test Vue components
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          export NPM_BIN=node_modules/.bin
          export PATH=$PATH:$NPM_BIN
          cat scripts/args.esbuild.dev-runner | xargs esbuild && env-cmd -e dev,vtu node build/dev-runner.js